### ISSUE TITLE
Remove unnecessary spaces

### ISSUE THREAD

**Issue by nirmal070125** [jnswso2/wso2-log-configurer#1]
```
tools java -jar wso2-log-configurer.jar update update-log.json 
Logging service started..

User authenticated successfully!

Reading logger changes from file...

Additivity not specified. Fetching current additivity..
Fetching additivity successful!
Log updated successfully for org.apache.synapse.transport
Logs updated successfully!

User logged out successfully
```

**Comment by jan1tha** [comment]
Now the logs should look like this

> Logging service started..
> User authenticated successfully!
> Reading logger changes from file...
> Additivity not specified. Fetching current additivity..
> Fetching additivity successful!
> Log updated successfully for API_LOGGER.HealthCheck
> Logs updated successfully!
> User logged out successfully
