### ISSUE TITLE
Once the operations done the user should logout properly 

### ISSUE THREAD

**Issue by nirmal070125** [jnswso2/wso2-log-configurer#6]
I see following is printing in update operation 

```
User logged out successfully
```

but can't see any logs in the server w.r.t. the logout. Logout happens properly right?

When I logged out from the UI, I see following log;

```
[2019-08-12 16:02:47,488]  INFO - AuthenticationAdmin 'admin@carbon.super [-1234]' logged out at [2019-08-12 16:02:47,0488]
```

**Comment by Kamidu** [comment]
@nirmal070125,
Please note that the this application triggeres Admin service calls to achive the end goal. We do not loginto the systems. hence there will be no logs indicating a log out. 
Please note as similer to the Admin service calls there will be log for each admin service invocation indication the configured user logged in to the system. That is the expected. Behavior. Please reopen this issue if there are any more concerns regarding this.

@jnswso2 Please close this issue as well.

**Comment by jan1tha** [comment]
Closing this issue.

@nirmal070125 please reopen the issue if there are any concerns.
